# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"\x16\n\x05\x46rame\x12\r\n\x05image\x18\x01 \x01(\x0c\"\xa4\x01\n\rPlateResponse\x12\x12\n\ncharacters\x18\x01 \x01(\t\x12\x12\n\nplate_type\x18\x02 \x01(\t\x12\x14\n\x0cplate_folder\x18\x03 \x01(\t\x12\x19\n\x11\x66ull_image_folder\x18\x04 \x01(\t\x12\x13\n\x0bplate_image\x18\x05 \x01(\x0c\x12\x12\n\nfull_image\x18\x06 \x01(\x0c\x12\x11\n\ttimestamp\x18\x07 \x01(\t2I\n\rPlateDatector\x12\x38\n\x0cStreamFrames\x12\r.server.Frame\x1a\x15.server.PlateResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=24
  _globals['_FRAME']._serialized_end=46
  _globals['_PLATERESPONSE']._serialized_start=49
  _globals['_PLATERESPONSE']._serialized_end=213
  _globals['_PLATEDATECTOR']._serialized_start=215
  _globals['_PLATEDATECTOR']._serialized_end=288
# @@protoc_insertion_point(module_scope)
